-- Logali HANA Guard webinar lab
-- Review with the HANA security administrator before execution.
-- Run object grants as the object owner or a principal with GRANT OPTION.

CREATE ROLE "N8N_WEBINAR_READ_ROLE";

GRANT SELECT ON "SAPHANADB"."T001"
  TO "N8N_WEBINAR_READ_ROLE";
GRANT SELECT ON "SAPHANADB"."VBAK"
  TO "N8N_WEBINAR_READ_ROLE";
GRANT SELECT ON "SAPHANADB"."ACDOCA"
  TO "N8N_WEBINAR_READ_ROLE";

CREATE USER "N8N_WEBINAR_RO"
  PASSWORD "REPLACE_WITH_A_GENERATED_SECRET"
  NO FORCE_FIRST_PASSWORD_CHANGE;

GRANT "N8N_WEBINAR_READ_ROLE" TO "N8N_WEBINAR_RO";

-- Positive smoke test as N8N_WEBINAR_RO:
-- SELECT "BUKRS", "BUTXT", "WAERS"
-- FROM "SAPHANADB"."T001"
-- LIMIT 5;

-- Negative tests as N8N_WEBINAR_RO; both must fail:
-- UPDATE "SAPHANADB"."T001"
-- SET "BUTXT" = "BUTXT"
-- WHERE 1 = 0;
--
-- SELECT * FROM "SAPHANADB"."USR02" LIMIT 1;
